### ISSUE TITLE
No servers available

### ISSUE THREAD

**Issue by GeoffreyPlitt** [memcachier/memjs#114]
This library is having trouble connecting to servers in Heroku. I get "No servers available" at least once a week for the last year. I have rebooted my Heroku instance many times, and there aren't any other customizations that could be causing this.

It's not just an error message, it seems that during these moments, get/set fails.

I have tried it with "Memcachier" and "Memcache Cloud" services in Heroku and it happened with both, so the problem is this library.

Any ideas?

**Comment by alevy** [comment]
@GeoffreyPlitt can you expand a bit more on the symptoms of the problem? How long until it recovers (if at all)? Does there seem to be any particular kind of event that triggers this?

In general, the "No servers available" error occurs when connections to all servers have failed in some way and each of their failover times has yet to expire (60 seconds by default, though that's tunable).

Since this is happening regardless of the server on the other end, the most likely case here is either an actual networking issue on the client machine, _or_ a rarely triggered bug (rare because I'm assuming once a week is a small percentage of requests, but that might be incorrect in your case) in the client library that basically incorrectly marks servers failed or somehow incorrectly breaks the connection (e.g. could be a failure of the protocol implementation).

Without some more detail it's really hard to distinguish what might be going on.

Have others seen similar behaviour?

**Comment by GeoffreyPlitt** [comment]
Super helpful answer! While reading this, I realized that the culprit may be a connection timeout that's too low at 1s. I'm going to close this now, will let you know if I find out anything useful. Thanks!
